### ISSUE TITLE
Application reject due to twitter login on external safari browser

### ISSUE THREAD

**Issue by fahadnaeem786** [didats/DTSocialMediaLogin#5]
Apple rejected my app because twitter singIn is done on external safari browser. They asked to use Safari View Controller inside the app to complete twitter signIn process. What changes should I perform to make this issue fix? 

DTTwitter perform OAuthSwift authorization by default OAuthSwiftOpenURLExternally.sharedInstance

**Comment by didats** [comment]
Hello @fahadnaeem786, 

Thank you for your feedback. Didn't realize your message since I didn't see your issue. It should be fixed with the new updates.
